parserOptions:
  ecmaVersion: 8
  sourceType: "module"
  ecmaFeatures:
    impliedStrict: true
    jsx: true

globals: 
  Promise: true
  document: true
  Vector: true
  read: true

env:
  browser: true
  node: true
  es6: true

plugins: 
  - "promise"
  - "flowtype"
  - "babel"
  - "react"

extends: 
  - "plugin:flowtype/recommended"
  - "eslint:recommended"
  - "plugin:react/recommended"

parser: "babel-eslint"

rules:
  key-spacing: ["error", { "beforeColon": true, "afterColon": true, "align": { "beforeColon": true, "on": "colon" } }]
  no-multi-spaces: ["error", { exceptions: { "VariableDeclarator": true } }]
  react/jsx-uses-react: "error"
  react/jsx-uses-vars: "error"
  react/no-unescaped-entities: 0
  babel/new-cap: 1
  babel/object-curly-spacing: 0
  babel/no-invalid-this: 1
  babel/semi: 0
  no-cond-assign: 0
  strict: 0
  object-curly-spacing: ["error", "always"]
  array-bracket-spacing: ["error", "always"]
  indent: ["error", 2]
  quotes: ["error", "single", { "allowTemplateLiterals": true,  "avoidEscape": true }]
  no-unused-vars: ["error", { "vars": "all", "args": "none", "ignoreRestSiblings": false }]
  keyword-spacing: ["error", { before: true, after: true }]
  space-before-function-paren: ["error", "always"]
  eqeqeq: ["error", "always"]
  space-infix-ops: "error"
  comma-spacing: ["error", { "before": false, "after": true }]
  brace-style: ["error", "stroustrup"]
  curly: ["error", "multi"]
  handle-callback-err: "error"
  no-undef: "error"
  no-multiple-empty-lines: ["error", { "max": 1, "maxEOF": 1 }]
  operator-linebreak: ["error", "after"]
  block-spacing: "error"
  comma-dangle: ["error", "never"]
  comma-style: ["error", "last"]
  dot-location: ["error", "property"]
  eol-last: ["error", "always"]
  func-call-spacing: ["error", "never"]
  new-cap: ["error", { "newIsCap": true }]
  constructor-super: "error"
  no-caller: "error"
  no-class-assign: "error"
  no-constant-condition: "error"
  no-control-regex: "error"
  no-debugger: "error"
  no-delete-var: "error"
  no-dupe-args: "error"
  no-dupe-class-members: "error"
  no-dupe-keys: "error"
  no-duplicate-case: "error"
  no-duplicate-imports: "error"
  no-empty-character-class: "error"
  no-empty-pattern: "error"
  no-ex-assign: "error"
  no-extend-native: "error"
  no-extra-bind: "error"
  no-extra-boolean-cast: "error"
  no-extra-parens: "error"
  no-fallthrough: "error"
  no-floating-decimal: "error"
  no-func-assign: "error"
  no-global-assign: "error"
  no-implied-eval: "error"
  no-inner-declarations: "error"
  no-invalid-regexp: "error"
  no-irregular-whitespace: "error"
  no-iterator: "error"
  no-label-var: "error"
  no-labels: "error"
  no-lone-blocks: "error"
  no-mixed-spaces-and-tabs: "error"
  no-multi-str: "error"
  no-new: "error"
  no-new-func: "error"
  no-new-object: "error"
  no-new-require: "error"
  no-new-symbol: "error"
  no-new-wrappers: "error"
  no-obj-calls: "error"
  no-octal: "error"
  no-octal-escape: "error"
  no-path-concat: "error"
  no-proto: "error"
  no-redeclare: "error"
  no-regex-spaces: "error"
  no-self-assign: "error"
  no-self-compare: "error"
  no-sequences: "error"
  no-shadow-restricted-names: "error"
  no-sparse-arrays: "error"
  no-tabs: "error"
  no-template-curly-in-string: "error"
  no-this-before-super: "error"
  no-trailing-spaces: "error"
  no-undef-init: "error"
  no-unmodified-loop-condition: "error"
  no-unneeded-ternary: "error"
  no-unreachable: "error"
  no-unsafe-finally: "error"
  no-unsafe-negation: "error"
  no-useless-call: "error"
  no-useless-computed-key: "error"
  no-useless-constructor: "error"
  no-useless-escape: "error"
  no-with: "error"
  object-property-newline: "error"
  padded-blocks: ["error", "never"]
  rest-spread-spacing: ["error", "always"]
  semi-spacing: "error"
  no-useless-rename: "error"
  no-whitespace-before-property: "error"
  space-before-blocks: "error"
  space-in-parens: ["error", "never"]
  space-unary-ops: "error"
  spaced-comment: ["error", "always"]
  template-curly-spacing: "error"
  use-isnan: "error"
  valid-typeof: "error"
  wrap-iife: ["error", "outside"]
  yield-star-spacing: ["error", "both"]
  yoda: "error"
  semi: ["error", "never"]
  no-unexpected-multiline: "error"
  promise/no-return-wrap: "error"
  promise/param-names: "error"
  promise/no-native: "off"
  promise/no-nesting: "warn"
