function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"src\u002Findex.pug":"doctype html\nhtml\n  head\n    meta(charset='utf-8')\n    title Algotithm\n    link(rel='shortcut icon', type='image\u002Fpng', href='icon\u002Ffavicon.svg')\n    link(rel='stylesheet', href='.\u002Fvendor\u002Fcodemirror\u002Flib\u002Fcodemirror.css')\n    link(rel='stylesheet', href='.\u002Fvendor\u002Fcodemirror\u002Ftheme\u002Fone-dark.css')\n    link(rel='stylesheet', href='.\u002Fvendor\u002Fcodemirror\u002Faddon\u002Fhint\u002Fshow-hint.css')\n    \u002F\u002F 1ink rel=\"stylesheet\" href=\".\u002Flook\u002Fbootstrap-reboot.min.css\"\n    script(src='.\u002Fcore\u002Fglobal.js')\n    script(src='.\u002Fcore\u002Ftabs.js')\n    \u002F\u002F CodeMirror\n    script(src='.\u002Fvendor\u002Fcodemirror\u002Flib\u002Fcodemirror.js')\n    script(src='.\u002Fvendor\u002Fcodemirror\u002Faddon\u002Fhint\u002Fshow-hint.js')\n    script(src='.\u002Fvendor\u002Fcodemirror\u002Faddon\u002Fhint\u002Fanyword-hint.js')\n    script(src='.\u002Fvendor\u002Fcodemirror\u002Fmode\u002Falgorithm\u002Falgorithm.es.js')\n    script(src='.\u002Fvendor\u002Fcodemirror\u002Fmode\u002Fjavascript\u002Fjavascript.js')\n    script(src='.\u002Fapp.js')\n    script(src='.\u002Fcore\u002Fconsole.js')\n    script(src='.\u002Fcore\u002Fvector.js')\n    script(src='.\u002Fcore\u002Falgorithm.js')\n    script(src='.\u002Fcore\u002Ficons.js')\n    link(rel='stylesheet', href='.\u002Flook\u002Fonedark.css', title='One Dark')\n  body\n    each value, index in {x:5,y:2}\n      p= value + ' ' + index\n    #ide.modal.hidden\n      .ide\n        ul\n          li#hamburger.tab-hamburger\n            img(src='.\u002Ficon\u002Fmenu.svg', width='26')\n    nav#tabs\n      ul\n        li#hamburger.tab-hamburger(onclick='hamburger_onclick()')\n          #menu.hamburger\n            img(src='.\u002Ficon\u002Fmenu.svg', width='24')\n        li#tab1.tab-active(onclick='tab(1);') Editor\n        li#tab2.tab(onclick='tab(2);algorithm.to_js();') Consola\n    #screen.screen\n      #content1.tab.show-content\n        textarea#code.caja.toolbox-space(name='code')\n          | algoritmo facilito\n          | variables\n          | numero, i, tabla[10]: entero\n          | inicio\n    |     \n    script.\n      \u002F\u002F all languages\n      var langs = ['es'];\n      \u002F\u002F default language\n      var dflt = 'es'\n      \u002F\u002F import language\n      var locale = window.navigator.language.substr(0,2);\n      if (langs.indexOf(locale) === -1)\n      locale = dflt;\n      var lang = document.createElement('script');\n      lang.src = `.\u002Flang\u002F${locale}.js`;\n      \u002F\u002F insert languaje\n      document.body.appendChild(lang);\n"};
;pug_debug_line = 1;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003C!DOCTYPE html\u003E";
;pug_debug_line = 2;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Chtml\u003E";
;pug_debug_line = 3;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Chead\u003E";
;pug_debug_line = 4;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cmeta charset=\"utf-8\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Ctitle\u003E";
;pug_debug_line = 5;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "Algotithm\u003C\u002Ftitle\u003E";
;pug_debug_line = 6;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Clink rel=\"shortcut icon\" type=\"image\u002Fpng\" href=\"icon\u002Ffavicon.svg\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Clink rel=\"stylesheet\" href=\".\u002Fvendor\u002Fcodemirror\u002Flib\u002Fcodemirror.css\"\u003E";
;pug_debug_line = 8;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Clink rel=\"stylesheet\" href=\".\u002Fvendor\u002Fcodemirror\u002Ftheme\u002Fone-dark.css\"\u003E";
;pug_debug_line = 9;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Clink rel=\"stylesheet\" href=\".\u002Fvendor\u002Fcodemirror\u002Faddon\u002Fhint\u002Fshow-hint.css\"\u003E";
;pug_debug_line = 10;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003C!-- 1ink rel=\"stylesheet\" href=\".\u002Flook\u002Fbootstrap-reboot.min.css\"--\u003E";
;pug_debug_line = 11;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fcore\u002Fglobal.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 12;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fcore\u002Ftabs.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 13;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003C!-- CodeMirror--\u003E";
;pug_debug_line = 14;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fvendor\u002Fcodemirror\u002Flib\u002Fcodemirror.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 15;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fvendor\u002Fcodemirror\u002Faddon\u002Fhint\u002Fshow-hint.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 16;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fvendor\u002Fcodemirror\u002Faddon\u002Fhint\u002Fanyword-hint.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 17;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fvendor\u002Fcodemirror\u002Fmode\u002Falgorithm\u002Falgorithm.es.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 18;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fvendor\u002Fcodemirror\u002Fmode\u002Fjavascript\u002Fjavascript.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 19;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fapp.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 20;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fcore\u002Fconsole.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 21;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fcore\u002Fvector.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 22;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fcore\u002Falgorithm.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 23;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript src=\".\u002Fcore\u002Ficons.js\"\u003E\u003C\u002Fscript\u003E";
;pug_debug_line = 24;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Clink rel=\"stylesheet\" href=\".\u002Flook\u002Fonedark.css\" title=\"One Dark\"\u003E\u003C\u002Fhead\u003E";
;pug_debug_line = 25;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cbody\u003E";
;pug_debug_line = 26;pug_debug_filename = "src\u002Findex.pug";
// iterate {x:5,y:2}
;(function(){
  var $$obj = {x:5,y:2};
  if ('number' == typeof $$obj.length) {
      for (var index = 0, $$l = $$obj.length; index < $$l; index++) {
        var value = $$obj[index];
;pug_debug_line = 27;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 27;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = value + ' ' + index) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
      }
  } else {
    var $$l = 0;
    for (var index in $$obj) {
      $$l++;
      var value = $$obj[index];
;pug_debug_line = 27;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 27;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = value + ' ' + index) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
    }
  }
}).call(this);

;pug_debug_line = 28;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"modal hidden\" id=\"ide\"\u003E";
;pug_debug_line = 29;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"ide\"\u003E";
;pug_debug_line = 30;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cul\u003E";
;pug_debug_line = 31;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cli class=\"tab-hamburger\" id=\"hamburger\"\u003E";
;pug_debug_line = 32;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cimg src=\".\u002Ficon\u002Fmenu.svg\" width=\"26\"\u003E\u003C\u002Fli\u003E\u003C\u002Ful\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 33;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cnav id=\"tabs\"\u003E";
;pug_debug_line = 34;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cul\u003E";
;pug_debug_line = 35;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cli class=\"tab-hamburger\" id=\"hamburger\" onclick=\"hamburger_onclick()\"\u003E";
;pug_debug_line = 36;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"hamburger\" id=\"menu\"\u003E";
;pug_debug_line = 37;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cimg src=\".\u002Ficon\u002Fmenu.svg\" width=\"24\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fli\u003E";
;pug_debug_line = 38;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cli class=\"tab-active\" id=\"tab1\" onclick=\"tab(1);\"\u003E";
;pug_debug_line = 38;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "Editor\u003C\u002Fli\u003E";
;pug_debug_line = 39;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cli class=\"tab\" id=\"tab2\" onclick=\"tab(2);algorithm.to_js();\"\u003E";
;pug_debug_line = 39;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "Consola\u003C\u002Fli\u003E\u003C\u002Ful\u003E\u003C\u002Fnav\u003E";
;pug_debug_line = 40;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"screen\" id=\"screen\"\u003E";
;pug_debug_line = 41;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"tab show-content\" id=\"content1\"\u003E";
;pug_debug_line = 42;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Ctextarea class=\"caja toolbox-space\" id=\"code\" name=\"code\"\u003E";
;pug_debug_line = 43;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "algoritmo facilito";
;pug_debug_line = 44;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 44;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "variables";
;pug_debug_line = 45;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 45;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "numero, i, tabla[10]: entero";
;pug_debug_line = 46;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\n";
;pug_debug_line = 46;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "inicio\u003C\u002Ftextarea\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 47;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "    ";
;pug_debug_line = 48;pug_debug_filename = "src\u002Findex.pug";
pug_html = pug_html + "\u003Cscript\u003E";
;pug_debug_line = 49;
pug_html = pug_html + "\u002F\u002F all languages";
;pug_debug_line = 50;
pug_html = pug_html + "\n";
;pug_debug_line = 50;
pug_html = pug_html + "var langs = ['es'];";
;pug_debug_line = 51;
pug_html = pug_html + "\n";
;pug_debug_line = 51;
pug_html = pug_html + "\u002F\u002F default language";
;pug_debug_line = 52;
pug_html = pug_html + "\n";
;pug_debug_line = 52;
pug_html = pug_html + "var dflt = 'es'";
;pug_debug_line = 53;
pug_html = pug_html + "\n";
;pug_debug_line = 53;
pug_html = pug_html + "\u002F\u002F import language";
;pug_debug_line = 54;
pug_html = pug_html + "\n";
;pug_debug_line = 54;
pug_html = pug_html + "var locale = window.navigator.language.substr(0,2);";
;pug_debug_line = 55;
pug_html = pug_html + "\n";
;pug_debug_line = 55;
pug_html = pug_html + "if (langs.indexOf(locale) === -1)";
;pug_debug_line = 56;
pug_html = pug_html + "\n";
;pug_debug_line = 56;
pug_html = pug_html + "locale = dflt;";
;pug_debug_line = 57;
pug_html = pug_html + "\n";
;pug_debug_line = 57;
pug_html = pug_html + "var lang = document.createElement('script');";
;pug_debug_line = 58;
pug_html = pug_html + "\n";
;pug_debug_line = 58;
pug_html = pug_html + "lang.src = `.\u002Flang\u002F${locale}.js`;";
;pug_debug_line = 59;
pug_html = pug_html + "\n";
;pug_debug_line = 59;
pug_html = pug_html + "\u002F\u002F insert languaje";
;pug_debug_line = 60;
pug_html = pug_html + "\n";
;pug_debug_line = 60;
pug_html = pug_html + "document.body.appendChild(lang);\u003C\u002Fscript\u003E\u003C\u002Fbody\u003E\u003C\u002Fhtml\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}